import '@rainbow-me/rainbowkit/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { ClientProviders } from '@/components/providers/ClientProviders'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const BASE_URL = new URL(
  process.env.NEXT_PUBLIC_BASE_URL ||
    process.env.VERCEL_PROJECT_PRODUCTION_URL ||
    ''
)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  other: {
    'fc:frame': JSON.stringify({
      version: 'next',
      imageUrl: `${BASE_URL}/img/opengraph.jpg`,
      button: {
        title: 'Play',
        action: {
          type: 'launch_frame',
          name: 'AI Game Show',
          url: `${BASE_URL}`,
          splashImageUrl: `${BASE_URL}/img/logo-square.svg`,
          splashBackgroundColor: '#f7f7f7',
        },
      },
    }),
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  )
}
